# Generated by Django 5.2.5 on 2025-08-27 21:53

import django.contrib.postgres.constraints
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_extension")
    ]

    operations = [
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'entity_type',
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happened_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.CharField(max_length=200)),
                ('module', models.CharField(default='crm', max_length=50)),
                ('entity_uuid', models.UUIDField(blank=True, null=True)),
                ('target_kind', models.CharField(max_length=80)),
                ('target_key', models.JSONField()),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('correlation_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'audit_event',
                'indexes': [models.Index(fields=['entity_uuid'], name='audit_event_entity__94e60b_idx'), models.Index(fields=['module', 'target_kind'], name='audit_event_module_e62fdd_idx')],
            },
        ),
        migrations.CreateModel(
            name='EntityDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_uuid', models.UUIDField(db_index=True)),
                ('detail_code', models.CharField(max_length=50)),
                ('value_kind', models.CharField(choices=[('TEXT', 'Text'), ('NUM', 'Numeric'), ('TS', 'Timestamp'), ('BOOL', 'Boolean'), ('JSON', 'JSON')], max_length=8)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_num', models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True)),
                ('value_ts', models.DateTimeField(blank=True, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('value_json', models.JSONField(blank=True, null=True)),
                ('hashdiff', models.CharField(db_index=True, max_length=64)),
            ],
            options={
                'db_table': 'entity_detail',
                'indexes': [models.Index(condition=models.Q(('is_current', True)), fields=['entity_uuid', 'detail_code'], name='ix_edetail_pair_current')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('entity_uuid', 'detail_code'), name='uniq_edetail_current'), django.contrib.postgres.constraints.ExclusionConstraint(expressions=[(models.F('entity_uuid'), '='), (models.F('detail_code'), '='), (models.Func(models.F('valid_from'), models.F('valid_to'), function='tstzrange'), '&&')], name='edetail_no_overlap'), models.CheckConstraint(condition=models.Q(models.Q(('value_kind', 'TEXT'), ('value_text__isnull', False)), models.Q(('value_kind', 'TEXT'), _negated=True), _connector='OR'), name='edetail_kind_text_chk'), models.CheckConstraint(condition=models.Q(models.Q(('value_kind', 'NUM'), ('value_num__isnull', False)), models.Q(('value_kind', 'NUM'), _negated=True), _connector='OR'), name='edetail_kind_num_chk'), models.CheckConstraint(condition=models.Q(models.Q(('value_kind', 'TS'), ('value_ts__isnull', False)), models.Q(('value_kind', 'TS'), _negated=True), _connector='OR'), name='edetail_kind_ts_chk'), models.CheckConstraint(condition=models.Q(models.Q(('value_bool__isnull', False), ('value_kind', 'BOOL')), models.Q(('value_kind', 'BOOL'), _negated=True), _connector='OR'), name='edetail_kind_bool_chk'), models.CheckConstraint(condition=models.Q(models.Q(('value_json__isnull', False), ('value_kind', 'JSON')), models.Q(('value_kind', 'JSON'), _negated=True), _connector='OR'), name='edetail_kind_json_chk')],
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_uuid', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('display_name', models.TextField()),
                ('hashdiff', models.CharField(db_index=True, max_length=64)),
                ('type_code', models.ForeignKey(db_column='type_code', on_delete=django.db.models.deletion.PROTECT, to='crm.entitytype')),
            ],
            options={
                'db_table': 'entity',
                'indexes': [models.Index(condition=models.Q(('is_current', True)), fields=['type_code'], name='ix_entity_type_current')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('entity_uuid',), name='uniq_entity_current'), django.contrib.postgres.constraints.ExclusionConstraint(expressions=[(models.F('entity_uuid'), '='), (models.Func(models.F('valid_from'), models.F('valid_to'), function='tstzrange'), '&&')], name='entity_no_overlap')],
            },
        ),
    ]
